name: mc_list

services:
    pg_db:
        container_name: ${CONTAINER_PREFIX}main_db
        image: postgres:17.2
        platform: linux/x86_64
        environment:
            POSTGRES_DB: ${PG_DATABASE}
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - '${PG_PORT}:5432'
        volumes:
            - ./.docker/postgres:/data

    minio:
        container_name: ${CONTAINER_PREFIX}storage
        image: quay.io/minio/minio:latest
        platform: linux/x86_64
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_REGION_NAME: ${MINIO_REGION_NAME}
        command: server --console-address ":9001" /data
        volumes:
            - ./.docker/minio:/data
        ports:
            - '${MINIO_PORT_CONSOLE}:9001'
            - '${MINIO_PORT_HOST}:9000'

    redis:
        container_name: ${CONTAINER_PREFIX}redis
        image: redis:7.4
        ports:
            - '${REDIS_PORT}:6379'
