name: mc_list

services:
    pg_db:
        container_name: ${CONTAINER_PREFIX}main_db
        image: postgres:17.2
        platform: linux/x86_64
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - ./.docker/postgres:/data

    redis:
        container_name: ${CONTAINER_PREFIX}redis
        image: redis:7.4
        ports:
            - '${REDIS_PORT}:6379'
