apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: frontend-ingress
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt
spec:
    rules:
        - host: __SITE_DOMAIN__
          http:
              paths:
                  - path: /?(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: frontend-service
                            port:
                                number: 80
